; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = espidf
upload_speed = 921600
monitor_speed = 115200


[platformio]
description = Diseñar e implementar una aplicación básica en un microcontrolador ESP32 utilizando una matriz de LEDs 8x8 bicolor (24 pines).   El proyecto consiste en desarrollar un videojuego sencillo, con entradas mediante pulsadores y uso de al menos dos colores de la matriz.
